apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
        - myapp.dev
        - grafana.local
        - prometheus.local
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: myapp-tls-cert   # Имя секрета, который мы создали
      hosts:
        - myapp.dev
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rest-vs
spec:
  hosts:
    - myapp.dev
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /rest-service
      route:
        - destination:
            host: rest-service
            port:
              number: 9080
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-vs
spec:
  hosts:
    - myapp.dev
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /db-service
      route:
        - destination:
            host: db-service
            port:
              number: 9081
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana-vs
spec:
  hosts:
    - grafana.local
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: monitoring-grafana
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: prometheus-vs
spec:
  hosts:
    - prometheus.local
  gateways:
    - my-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: monitoring-kube-prometheus-prometheus
            port:
              number: 9090
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: grafana-dr
spec:
  host: monitoring-grafana
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: prometheus-dr
spec:
  host: monitoring-kube-prometheus-prometheus
  trafficPolicy:
    tls:
      mode: DISABLE